proyectoFinal/proyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('apps.gestion_clientes.urls')),
    path('productos/', include('apps.gestion_productos.urls')),
    path('comprarProducto/', include('apps.compra_farmacia.urls')),
    path('login/', include('apps.login.urls')),
    path('', views.index, name='homepage'),
]

proyectoFinal/apps/modelo/models.py
from django.db import models

class Cliente(models.Model):
    listaGenero = (
        ('femenino','Femenino'),
        ('masculino', 'Masculino')
    )
    cliente_id = models.AutoField(primary_key = True)
    cedula = models.CharField(max_length = 10, unique = True, null = False)
    nombres = models.CharField(max_length = 70, null = False)
    apellidos = models.CharField(max_length = 70, null = False)
    genero = models.CharField(max_length = 30, choices = listaGenero, default = 'masculino')
    correo = models.EmailField(max_length = 105, null = False)
    telefono = models.CharField(max_length = 15, null = False)
    direccion = models.TextField(max_length = 200)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__ (self):
        return self.cedula


class Producto(models.Model):
    producto_id = models.AutoField(primary_key = True)
    codigo = models.IntegerField(unique = True, null = False)
    nombre = models.CharField(max_length = 70, null = False)
    stock = models.IntegerField(unique = True, null = False)
    precio_Unitario = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    date_created = models.DateTimeField(auto_now_add = True)
         
    def __str__(self):
        return self.codigo



class Compra(models.Model):
    compra_id = models.AutoField(primary_key = True)
    fecha = models.DateTimeField(auto_now_add = True, null = False)
    numero_Productos = models.IntegerField(null = False)
    valor_Total = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    descripcion = models.TextField(default = 'Descripción de la compra')
    product = models.ForeignKey(Producto, on_delete = models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
    date_created = models.DateTimeField(auto_now_add = True)
    updated_ad = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.compra_id

proyectoFinal/templates/clientes/crear.html
{% extends "master.html" %}

{% block contenido %}
<h2>Crear Cliente</h2>
<form method="POST"> {% csrf_token %}
    <h4><strong>Datos del Cliente</strong></h4>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_cedula">Cedula</label>
            <input type="text" class="form-control" name="cedula" maxlength="10" required id="id_cedula">
        </div>
        <div class="form-group col-md-4">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" class="form-control" name="apellidos" maxlength="70" required id="id_apellidos">
        </div>
        <div class="form-group col-md-4">
            <label for="id_nombres">Nombres:</label>
            <input type="text" class="form-control" name="nombres" maxlength="70" required id="id_nombres">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_genero">Genero:</label>

            <select name="genero" id="id_genero" class="form-control">
                <option value="femenino">Femenino</option>

                <option value="masculino">Masculino</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="id_correo">Correo:</label>
        <input type="email" class="form-control" name="correo" maxlength="105" required id="id_correo"></p>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_telefono">Telefono:</label>
            <input type="text" class="form-control" name="telefono" maxlength="15" required id="id_telefono">
        </div>
    </div>
    <div class="form-group">
        <label for="id_direccion">Direccion:</label>
        <textarea name="direccion" class="form-control" maxlength="200" required id="id_direccion"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Crear Cliente</button>
</form>
{% endblock %}

proyectoFinal/templates/clientes/index.html
{% extends "master.html" %}
{% block contenido %}
<h4>Lista de Cliente</h4>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Cédula</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Nombres</th>
            <th scope="col">Correo</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for cliente in listaClientes%}
        <tr>
            <td>{{cliente.cedula}}</td>
            <td>{{cliente.apellidos}}</td>
            <td>{{cliente.nombres}}</td>
            <td>{{cliente.correo}}</td>
            <td>
                <a href="{% url 'eliminar_cliente' cliente.cedula %}"><i class="bi bi-trash"></i></a>
                <a href="{% url 'modificar_cliente' cliente.cedula %}"><i class="bi bi-pencil"></i></a>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <th scope="row" colspan="5">Añadir nuevo Cliente <a href="{% url 'crear_cliente' %}"><i
                        class="bi bi-plus-circle"></i></a></th>
        </tr>
    </tbody>
</table>
{% endblock %}

proyectoFinal/templates/clientes/modificar.html
{% extends "master.html" %}
{% block contenido %}

<h4>Modificar Cliente</h4>
<form method="POST"> {% csrf_token %}
    <h3>Datos del Cliente</h3>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_cedula">Cedula</label>
            <input type="text" class="form-control" name="cedula" maxlength="10" required id="id_cedula" value="{{ formulario_cliente.cedula.value }}">
        </div>
        <div class="form-group col-md-4">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" class="form-control" name="apellidos" maxlength="70" required id="id_apellidos" value="{{ formulario_cliente.apellidos.value }}">
        </div>
        <div class="form-group col-md-4">
            <label for="id_nombres">Nombres:</label>
            <input type="text" class="form-control" name="nombres" maxlength="70" required id="id_nombres" value="{{ formulario_cliente.nombres.value }}">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_genero">Genero:</label>

            <select name="genero" id="id_genero" class="form-control">
                {% if formulario_cliente.genero.value == 'femenino' %}
                <option value="femenino" selected>Femenino</option>
                <option value="masculino">Masculino</option>
                {% elif formulario_cliente.genero.value == 'masculino' %}
                <option value="femenino">Femenino</option>
                <option value="masculino" selected>Masculino</option>
                {% endif %}
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="id_correo">Correo:</label>
        <input type="email" class="form-control" name="correo" maxlength="105" required id="id_correo" value="{{ formulario_cliente.correo.value }}">
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_telefono">Telefono:</label>
            <input type="text" class="form-control" name="telefono" maxlength="15" required id="id_telefono" value="{{ formulario_cliente.telefono.value }}">
        </div>
    </div>
    <div class="form-group">
        <label for="id_direccion">Direccion:</label>
        <textarea name="direccion" class="form-control" cols="40" rows="10" maxlength="200" required
            id="id_direccion" value="">{{ formulario_cliente.direccion.value }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Modificar Cliente</button>
</form>
{% endblock %}