proyectoFinal/proyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('apps.gestion_clientes.urls')),
    path('productos/', include('apps.gestion_productos.urls')),
    path('comprarProducto/', include('apps.compra_farmacia.urls')),
    path('login/', include('apps.login.urls')),
    path('', views.index, name='homepage'),
]

proyectoFinal/apps/modelo/models.py
from django.db import models

class Cliente(models.Model):
    listaGenero = (
        ('femenino','Femenino'),
        ('masculino', 'Masculino')
    )
    cliente_id = models.AutoField(primary_key = True)
    cedula = models.CharField(max_length = 10, unique = True, null = False)
    nombres = models.CharField(max_length = 70, null = False)
    apellidos = models.CharField(max_length = 70, null = False)
    genero = models.CharField(max_length = 30, choices = listaGenero, default = 'masculino')
    correo = models.EmailField(max_length = 105, null = False)
    telefono = models.CharField(max_length = 15, null = False)
    direccion = models.TextField(max_length = 200)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__ (self):
        return self.cedula


class Producto(models.Model):
    producto_id = models.AutoField(primary_key = True)
    codigo = models.IntegerField(unique = True, null = False)
    nombre = models.CharField(max_length = 70, null = False)
    stock = models.IntegerField(unique = True, null = False)
    precio_Unitario = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    date_created = models.DateTimeField(auto_now_add = True)
         
    def __str__(self):
        return self.codigo



class Compra(models.Model):
    compra_id = models.AutoField(primary_key = True)
    fecha = models.DateTimeField(auto_now_add = True, null = False)
    numero_Productos = models.IntegerField(null = False)
    valor_Total = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    descripcion = models.TextField(default = 'Descripción de la compra')
    product = models.ForeignKey(Producto, on_delete = models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
    date_created = models.DateTimeField(auto_now_add = True)
    updated_ad = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.compra_id

proyectoFinal/templates/productos/crear.html
{% extends "master.html" %}

{% block contenido %}
<h2>Crear Producto</h2>
<form method="POST"> {% csrf_token %}
    <h4><strong>Datos del Producto</strong></h4>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_codigo">Codigo</label>
            <input type="text" class="form-control" name="codigo" maxlength="10" required id="id_codigo">
        </div>
        <div class="form-group col-md-4">
            <label for="id_nombre">Nombre:</label>
            <input type="text" class="form-control" name="nombre" maxlength="70" required id="id_nombre">
        </div>
        <div class="form-group col-md-2">
            <label for="id_stock">Stock:</label>
            <input type="text" class="form-control" name="stock" maxlength="70" required id="id_stock">
        </div>
        <div class="form-group col-md-2">
            <label for="id_stock">Precio Unitario:</label>
            <input type="text" class="form-control" name="precio_Unitario" maxlength="70" required id="id_precio_Unitario">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Crear Producto</button>
</form>
{% endblock %}

proyectoFinal/templates/productos/index.html
{% extends "master.html" %}
{% block contenido %}
<h4>Lista de Productos</h4>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombre</th>
            <th scope="col">Stock</th>
            <th scope="col">Precio Unitario</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in listaProductos%}
        <tr>
            <td>{{producto.codigo}}</td>
            <td>{{producto.nombre}}</td>
            <td>{{producto.stock}}</td>
            <td>{{producto.precio_Unitario}}</td>
            <td>
                <a href="{% url 'eliminar_producto' producto.codigo %}"><i class="bi bi-trash"></i></a>
                <a href="{% url 'modificar_producto' producto.codigo %}"><i class="bi bi-pencil"></i></a>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <th scope="row" colspan="5">Añadir nuevo Producto <a href="{% url 'crear_producto' %}"><i
                        class="bi bi-plus-circle"></i></a></th>
        </tr>
    </tbody>
</table>
{% endblock %}

proyectoFinal/templates/productos/modificar.html
{% extends "master.html" %}
{% block contenido %}

<h4>Modificar Producto</h4>
<form method="POST"> {% csrf_token %}
    <h3>Datos del Producto</h3>
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="id_codigo">Codigo</label>
            <input type="text" class="form-control" name="codigo" maxlength="10" required id="id_codigo" value="{{ formulario_producto.codigo.value }}">
        </div>
        <div class="form-group col-md-4">
            <label for="id_nombre">Nombre:</label>
            <input type="text" class="form-control" name="nombre" maxlength="70" required id="id_nombre" value="{{ formulario_producto.nombre.value }}">
        </div>
        <div class="form-group col-md-2">
            <label for="id_stock">Stock:</label>
            <input type="text" class="form-control" name="stock" maxlength="70" required id="id_stock" value="{{ formulario_producto.stock.value }}">
        </div>
        <div class="form-group col-md-2">
            <label for="id_precio_unitario">Precio Unitario</label>
            <input type="text" class="form-control" name="precio_Unitario" maxlength="10" required id="id_precio_Unitario" value="{{ formulario_producto.precio_Unitario.value }}">
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Modificar Producto</button>
</form>
{% endblock %}