proyectoFinal/proyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('apps.gestion_clientes.urls')),
    path('productos/', include('apps.gestion_productos.urls')),
    path('comprarProducto/', include('apps.compra_farmacia.urls')),
    path('login/', include('apps.login.urls')),
    path('', views.index, name='homepage'),
]

proyectoFinal/apps/modelo/models.py
from django.db import models

class Cliente(models.Model):
    listaGenero = (
        ('femenino','Femenino'),
        ('masculino', 'Masculino')
    )
    cliente_id = models.AutoField(primary_key = True)
    cedula = models.CharField(max_length = 10, unique = True, null = False)
    nombres = models.CharField(max_length = 70, null = False)
    apellidos = models.CharField(max_length = 70, null = False)
    genero = models.CharField(max_length = 30, choices = listaGenero, default = 'masculino')
    correo = models.EmailField(max_length = 105, null = False)
    telefono = models.CharField(max_length = 15, null = False)
    direccion = models.TextField(max_length = 200)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__ (self):
        return self.cedula


class Producto(models.Model):
    producto_id = models.AutoField(primary_key = True)
    codigo = models.IntegerField(unique = True, null = False)
    nombre = models.CharField(max_length = 70, null = False)
    stock = models.IntegerField(unique = True, null = False)
    precio_Unitario = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    date_created = models.DateTimeField(auto_now_add = True)
         
    def __str__(self):
        return self.codigo



class Compra(models.Model):
    compra_id = models.AutoField(primary_key = True)
    fecha = models.DateTimeField(auto_now_add = True, null = False)
    numero_Productos = models.IntegerField(null = False)
    valor_Total = models.DecimalField(max_digits = 10, decimal_places = 2, null = False)
    descripcion = models.TextField(default = 'Descripción de la compra')
    product = models.ForeignKey(Producto, on_delete = models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
    date_created = models.DateTimeField(auto_now_add = True)
    updated_ad = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.compra_id

proyectoFinal/templates/compra/comprarProducto.html
{% extends "master.html" %}
{% block contenido %}

<h2>Compra</h2>
<table class="table">
    <tbody>
        <td><strong>Cliente: </strong> {{cliente.nombres}} {{cliente.apellidos}}</td>
        <td><strong>Cedula: </strong>{{cliente.cedula}}</td>
        <td><strong>Correo: </strong>{{cliente.correo}}</td>
    </tbody>
</table>
<table class="table">
    <tbody>
        <td><strong>Nombre Producto: </strong> {{producto.nombre}} </td>
        <td><strong>Precio Unitario: </strong>{{producto.precio_Unitario}}</td>
        <td><strong>Stock: </strong>{{producto.stock}}</td>
    </tbody>
</table>
<form method="POST"> {% csrf_token %}
    <h4><strong>Ingrese la información</strong></h4>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_numero_Productos">Numero de Productos a Comprar</label>
            <input type="number" class="form-control" name="numero_Productos" required id="id_numero_Productos">
        </div>
        <div class="form-group col-md-6">
            <label for="id_descripcion">Descripcion:</label>
            <textarea class="form-control" name="descripcion" cols="10" rows="2" required id="id_descripcion"></textarea>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Comprar</button>
</form>
<p>{{ mensaje }}</p>
{% endblock %}

proyectoFinal/templates/compra/selectCliente.html
{% extends "master.html" %}
{% block contenido %}
<h4>Lista de Cliente</h4>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Cédula</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Nombres</th>
            <th scope="col">Correo</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for cliente in listaClientes%}
        <tr>
            <td>{{cliente.cedula}}</td>
            <td>{{cliente.apellidos}}</td>
            <td>{{cliente.nombres}}</td>
            <td>{{cliente.correo}}</td>
            <td>
                <a href="{% url 'seleccion_Producto' cliente.cedula "0" %}"><i class="bi bi-check-circle"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

proyectoFinal/templates/compra/selectProducto.html
{% extends "master.html" %}
{% block contenido %}
<h4>Lista de Productos</h4>
<table class="table">
    <tbody>
        <td><strong>Cliente: </strong> {{cliente.nombres}} {{cliente.apellidos}}</td>
        <td><strong>Cedula: </strong>{{cliente.cedula}}</td>
        <td><strong>Correo: </strong>{{cliente.correo}}</td>
    </tbody>
</table>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombre</th>
            <th scope="col">Stock</th>
            <th scope="col">Precio Unitario</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in listaProductos%}
        <tr>
            <td>{{producto.codigo}}</td>
            <td>{{producto.nombre}}</td>
            <td>{{producto.stock}}</td>
            <td>{{producto.precio_Unitario}}</td>
            <td>
                 <a href="{% url 'comprar' cedula producto.codigo total %}"><i class="bi bi-check-circle"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'terminar_Compra' cedula total %}">Terminar Compra <i class="bi bi-check-circle"></i></a>
{% endblock %}

proyectoFinal/templates/compra/totalCompra.html
{% extends "master.html" %}
{% block contenido %}
<table class="table">
    <tbody>
        <td><strong>Cliente: </strong> {{cliente.nombres}} {{cliente.apellidos}}</td>
        <td><strong>Cedula: </strong>{{cliente.cedula}}</td>
        <td><strong>Correo: </strong>{{cliente.correo}}</td>
    </tbody>
</table>
<p><strong>Total a pagar: </strong>{{ total }}</p>

{% endblock %}